# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
trigger:
  branches:
      include:
            - main

            schedules:
              - cron: "0 * * * *"
                  displayName: Hourly build
                      branches:
                            include:
                                    - main

                                    pool:
                                      vmImage: 'ubuntu-latest'

                                      steps:
                                      - script: echo "This pipeline runs every hour"
                                        displayName: 'Run hourly task'